# Dockerfile.frontend

# Imagem base
FROM python:3.12.2

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos de dependências e instalar
COPY frontend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copiar o restante dos arquivos do projeto
COPY . /app

# Comando para executar a aplicação
#CMD ["streamlit", "run", "app.py", "--server.port=8501"]